rasa-action-server:
  registry: docker.io/devopswithbrian

  extraEnv:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: jasper-prd
          key: API_KEY
    - name: FAUNA_KEY
      valueFrom:
        secretKeyRef:
          name: jasper-prd
          key: FAUNA_KEY

  image:
    name: "jasper-actions"
    tag: "latest"
    pullPolicy: Always