rasa-action-server:
  registry: docker.io/devopswithbrian

  extraEnv:
    - name: NASA_API_KEY
      valueFrom:
        secretKeyRef:
          name: jasper-prd
          key: NASA_API_KEY
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: jasper-prd
          key: GITHUB_TOKEN
    - name: FAUNA_KEY
      valueFrom:
        secretKeyRef:
          name: jasper-prd
          key: FAUNA_KEY
    - name: OPENAI_KEY
      valueFrom:
        secretKeyRef:
          name: jasper-prd
          key: OPENAI_KEY

  image:
    name: "jasper-actions"
    tag: "latest"
    pullPolicy: Always