apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rasa
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add labels to your application object.
  labels:
    name: rasa
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    helm:
      valueFiles:
        - rasa-values.yaml
    path: rasa/rasa
    repoURL: https://helm.rasa.com  # Can point to either a Helm chart repo or a git repo.
    targetRevision: HEAD

  # Destination cluster and namespace to deploy the application
  destination:
    # cluster API URL
    server: https://kubernetes.default.svc


  # RevisionHistoryLimit limits the number of items kept in the application's revision history, which is used for
  # informational purposes as well as for rollbacks to previous versions. This should only be changed in exceptional
  # circumstances. Setting to zero will store no history. This will reduce storage used. Increasing will increase the
  # space used to store the history, so we do not recommend increasing it.
  revisionHistoryLimit: 10
