applicationSettings:
  debugMode: true
  initialModel: "https://github.com/DevOps-With-Brian/chatbot-auto-versioning/releases/download/0.3.1/model_0.3.1.tar.gz?raw=true"
  credentials:
    additionalChannelCredentials:
      socketio:
        user_message_evt: user_uttered
        bot_message_evt: bot_uttered
        session_persistence: false
image:
  tag: "3.3.0"
nginx:
  enabled: false
ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: 'nginx',
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  }
  path: "/"
  hostname: rasa.devopswithbrian.com
  tls:
    - secretName: rasa-tls
      hosts:
        - rasa.devopswithbrian.com